### ISSUE TITLE
Hapi.createServer is not a function

### ISSUE THREAD

**Issue by foobar1123** [lefos987/generator-ghurt#21]
const server = Hapi.createServer('0.0.0.0', config.port, options);
                    ^

TypeError: Hapi.createServer is not a function
    at Object.<anonymous> (/srv/www/server/server.js:17:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
DEBUG: Program node server.js exited with code 1

DEBUG: Starting child process with 'node server.js'
/srv/www/server/server.js:17
const server = Hapi.createServer('0.0.0.0', config.port, options);

**Comment by umair-khanzada** [comment]
@Naranbat1123: can you solve this issue ?
